#!/bin/bash

#SBATCH --job-name=checkcount
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --time=03:22:00
#SBATCH --account=OGS23_PRACE_IT
#SBATCH --partition=g100_all_serial

source /g100_work/OGS23_PRACE_IT/COPERNICUS/py_env_3.9.18/bin/activate

python count_file_serial.py
sh count_files_downloaded.sh

python final_check_count.py
